# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
  jobs:
    pre_install:
      # Install uv package manager
      - make install-uv
    install:
      # Use uv to install project dependencies
      - make .venv

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
